[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install Flask==2.3.3"]

[start]
cmd = "python app.py"

[variables]
PYTHONPATH = "/app"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
