[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install -r requirements-minimal.txt --no-cache-dir"
]

[phases.build]
cmds = ["echo '🚀 Railway-optimized Trading System ready'"]

[start]
cmd = "gunicorn app_railway:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --preload"

[variables]
PYTHONPATH = "/app"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
TF_CPP_MIN_LOG_LEVEL = "2"
