[build]
  nixpkgs = [
    'python311',
    'python311Packages.pip',
    'python311Packages.setuptools', 
    'python311Packages.wheel',
    'python311Packages.flask',
    'python311Packages.flask-cors',
    'python311Packages.requests',
    'python311Packages.pandas',
    'python311Packages.numpy',
    'python311Packages.python-dotenv',
    'python311Packages.markupsafe',
    'python311Packages.jinja2',
    'python311Packages.click',
    'python311Packages.blinker',
    'python311Packages.itsdangerous',
    'python311Packages.python-dateutil',
    'python311Packages.pytz',
    'python311Packages.six',
    'bash'
  ]

[phases.setup]
  nixPkgs = [
    'python311',
    'python311Packages.flask',
    'python311Packages.requests',
    'python311Packages.pandas', 
    'python311Packages.numpy'
  ]
  
[phases.install]
  cmds = [
    'echo "🔧 Railway Nix Build Process Starting..."',
    'echo "🐍 Python location: $(which python3 || echo not found)"',
    'python3 --version || echo "Python3 not available"',
    'echo "📦 Verifying Nix packages are available..."',
    'python3 -c "import flask; print(f\"✅ Flask {flask.__version__} available from Nix\")" || echo "❌ Flask not available"',
    'python3 -c "import requests; print(f\"✅ Requests available from Nix\")" || echo "❌ Requests not available"',
    'python3 -c "import pandas; print(f\"✅ Pandas {pandas.__version__} available from Nix\")" || echo "❌ Pandas not available"',
    'python3 -c "import numpy; print(f\"✅ NumPy {numpy.__version__} available from Nix\")" || echo "❌ NumPy not available"',
    'echo "🎯 All core packages verified - skipping pip installation"',
    'echo "✅ Nix package verification complete"'
  ]

[start]
  cmd = 'python3 start.py'
  
[env]
  PYTHONPATH = '/app'
  FLASK_APP = 'app.py'
  PORT = '8080'
  PYTHONUSERBASE = '/app/.local'
