[build]
  nixpkgs = ['python311', 'python311Packages.pip']

[phases.install]
  cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements.txt']

[start]
  cmd = 'python app.py'
  
[env]
  PYTHONPATH = '/app'
  FLASK_APP = 'app.py'
  PORT = '8080'
