[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements-railway.txt"
]

[phases.build]
cmds = ["echo '🚀 Trading Analysis System ready for Railway'"]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn app_railway:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --max-requests 1000 --preload"

[variables]
PYTHONPATH = "/app"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
TF_CPP_MIN_LOG_LEVEL = "2"
