[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install Flask==2.3.3 requests numpy"
]

[phases.build]
cmds = ["echo '🚀 Bombastic Trading System ready for Railway'"]

[start]
cmd = ". /opt/venv/bin/activate && python app.py"

[variables]
PYTHONPATH = "/app"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
