# 🚀 JAX AI Trading System - Railway Configuration

[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "5001"
PYTHONUNBUFFERED = "1"
JAX_PLATFORM_NAME = "cpu"
JAX_ENABLE_X64 = "true"
FLASK_ENV = "production"
