[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
healthcheckPath = "/api/status"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production.variables]
FLASK_ENV = "production"
PYTHONPATH = "/app"